import PDFDocument from "pdfkit";

const formatDateTime = (d) => {
  try {
    return new Date(d).toLocaleString();
  } catch {
    return "";
  }
};

const formatMoney = (n) => {
  const value = typeof n === "number" ? n : Number(n || 0);
  return `₹${value.toFixed(2)}`;
};

export const generateBookingReceiptPdf = async ({ booking, customer, vehicle, paymentStatus, paymentMethod, bookingTime }) => {
  const doc = new PDFDocument({ margin: 40 });

  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));

  const endPromise = new Promise((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  const b = booking;
  const c = customer;
  const v = vehicle;

  // Header
  doc
    .fontSize(20)
    .fillColor("#111827")
    .text("RentRide Receipt", { align: "left" });

  doc.moveDown(0.5);
  doc
    .fontSize(10)
    .fillColor("#6b7280")
    .text("Booking confirmation", { align: "left" });

  doc.moveDown(1.5);

  doc
    .fontSize(12)
    .fillColor("#111827")
    .text(`Booking ID: ${b?.bookingNumber || ""}`);

  doc.fontSize(10).fillColor("#6b7280").text(`Booking Time: ${formatDateTime(bookingTime || b?.createdAt)}`);

  doc.moveDown(1);

  // Customer block
  doc.fontSize(12).fillColor("#111827").text("Customer");
  doc
    .fontSize(10)
    .fillColor("#374151")
    .text(`Name: ${c?.name || ""}`)
    .text(`Email: ${c?.email || ""}`)
    .text(`Phone: ${c?.phone || ""}`);

  doc.moveDown(1);

  // Vehicle block
  doc.fontSize(12).fillColor("#111827").text("Vehicle");
  doc
    .fontSize(10)
    .fillColor("#374151")
    .text(`${v?.name || ""}`)
    .text(`${v?.brand || ""} ${v?.model || ""}`.trim())
    .text(`License Plate: ${v?.licensePlate || ""}`)
    .text(`Category: ${v?.category || ""} · Transmission: ${v?.transmission || ""}`);

  doc.moveDown(1);

  // Dates
  doc.fontSize(12).fillColor("#111827").text("Rental period");
  doc
    .fontSize(10)
    .fillColor("#374151")
    .text(`Pickup: ${formatDateTime(b?.pickupDate)}`)
    .text(`Return: ${formatDateTime(b?.returnDate)}`);

  doc.moveDown(1);

  // Amount + status
  doc.fontSize(12).fillColor("#111827").text("Payment");
  doc
    .fontSize(10)
    .fillColor("#374151")
    .text(`Amount: ${formatMoney(b?.totalPrice)}`)
    .text(`Payment Status: ${paymentStatus || b?.paymentStatus || ""}`)
    .text(`Payment Method: ${paymentMethod || ""}`);

  doc.moveDown(2);

  // Footer
  doc
    .fontSize(9)
    .fillColor("#9ca3af")
    .text("This receipt was generated by RentRide. Thank you for choosing us!", { align: "left" });

  doc.end();

  return endPromise;
};

